### ISSUE TITLE
Value stack is not cleared between ParseRunner.run() calls

### ISSUE THREAD

**Issue by hatstand0** [fge/grappa#24]
I'm updating [some code](https://github.com/hatstand0/Staskken/tree/master/Parser) from 1.0.4 to 2.0.0-beta.1

Everything works correctly, with the sole exception of the value stack retaining its contents from previous runs using the same ParseRunner instance.

Is this an intended change, or a regression?

**Comment by fge** [comment]
Hmm, that is strange.

Can you link to the code where you invoke the parse runner?

**Comment by hatstand0** [comment]
All tests [here](https://github.com/hatstand0/Staskken/blob/master/Parser/src/test/java/TextParserTest.java) except for the first one, fail due to constraints on the value stack size (Expecting a single element only)

**Comment by fge** [comment]
Huuh, OK, that is indeed a regression... And I know why it's happening.

Time for -beta.2... Mind if I "steal" some of your code for writing a failing test?

**Comment by hatstand0** [comment]
Cool. And feel free, it's pretty trivial code.

**Comment by fge** [comment]
OK, on the other hand there's the problem of listeners; I need to think of a solution here. But this problem of yours is a definite one and a true regression, so I'll fix it.

I have an API in the corner of my mind but not now :p

**Comment by fge** [comment]
OK, 2.0.0-beta.2 has just been published on maven central.

Can you please confirm when you have updated the dependency and run your tests again?

**Comment by hatstand0** [comment]
Looks good, all tests are passing on my end

**Comment by fge** [comment]
OK, good. Closing, then.

Thanks for the bug report!
