### ISSUE TITLE
enforceVersion for build is too strict

### ISSUE THREAD

**Issue by jottinger** [fge/grappa#35]
enforceVersion mandates 1.7, exactly, even with source version set to 1.7; this means that compilation with gradle fails if the user has 1.8 installed. Should be more lenient IMO.

**Comment by fge** [comment]
In fact, an existing pull request had a better solution for that: only enforce the version when publishing artifacts.

I have picked this one instead, sorry :)

**Comment by jottinger** [comment]
That's fine. :) Include the .gitignore one though :)
