### ISSUE TITLE
Possibly contradicting parse error indicators

### ISSUE THREAD

**Issue by akirschbaum** [fge/grappa#6]
In ParsingResult there are two different indicators whether a parsing error has occurred: matched and parseErrors. Is it possible that _!matched_ but _parseErrors.isEmpty()_? If so: which error message should the application using the parser print? If not: why do both indicators exist at all?

I'd suggest that matched is removed. A parse should be successful if and only if no parse errors did occur.

**Comment by fge** [comment]
Too late for 1.0.x. Plans for 2.0.x however;
